### ISSUE TITLE
When will the training framework for human_parsing or human_pose be released

### ISSUE THREAD

**Issue by APeiZou** [tinyvision/SOLIDER#3]
@cwhgn Hello, When will the training framework for human_parsing or human_pose be released?

**Comment by XianzheXu** [comment]
@APeiZou  Thanks for your attentions, the code for human pose and human parsing will be released at the end of April.

**Comment by APeiZou** [comment]
thanks。



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/17/2023 19:00 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [tinyvision/SOLIDER] When will the training framework for human_parsing or human_pose be released (Issue #3) |

@APeiZou Thanks for your attentions, the code for human pose and human parsing will be released at the end of April.

**Comment by APeiZou** [comment]
@XianzheXu 哈喽，LUPerson dataset训练的模型用来对图片进行语义分割的示例代码有吗

**Comment by APeiZou** [comment]
@XianzheXu   @cwhgn  您好，教师模型的参数不通过反向传播，是直接复用的学生网络参数的吗？

**Comment by cwhgn** [comment]
> @XianzheXu @cwhgn 您好，教师模型的参数不通过反向传播，是直接复用的学生网络参数的吗？

是的，这个设置和DINO是完全一样的，教师模型的更新采用EMA。

**Comment by APeiZou** [comment]
@cwhgn 哈喽，论文里面的语义分类的3类为上半身人体，下半身人体，脚部，可以自己训练一个4类（人头，人体上半身，人体下半身，脚部）吗？如果自己随意定义一个4类模型能收敛吗？    或者说可以在自己的数据集上用你们提供的预训练模型训练吗？

**Comment by cwhgn** [comment]
可以收敛的，我们在补充材料中尝试了3-5类，结果上略微有些差异，但都能收敛且都符合结论规律的。另外，用自己数据训练也是可以的，我们也尝试过用大量业务场景无标注人体数据训练，效果甚至要好于LUPerson。

**Comment by APeiZou** [comment]
@cwhgn  感谢您的解答， 这种方法可以用在CNN网络的预训练上面吗？

**Comment by cwhgn** [comment]
我们的实验和之前的自监督方法类似(比如DNIO)，主要都集中在transformer based的框架上。CNN网络目前还没有尝试过。
