### ISSUE TITLE
LUPerson 官方链接提供的数据有10683716张数据，跟论文里面说的418万数据量好像不一致 

### ISSUE THREAD

**Issue by APeiZou** [tinyvision/SOLIDER#5]
@cwhgn 您好，LUPerson 官方链接提供的数据有10683716张数据，跟论文里面说的418万数据量好像不一致 ，是需要做什么处理变成418万的数据量吗？

**Comment by cwhgn** [comment]
我们使用的是LUPerson，即https://github.com/DengpanFu/LUPerson ，它一共有4M的图片。之前的链接有些问题，可能造成了误导，感谢您的提醒，我们已经更正了。另外，我们相信更大的数据量，比如LUPerson-NL，可以达到一个更好的效果。

**Comment by APeiZou** [comment]
@cwhgn 好的
